apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-claim
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  volumeName: server-pv
