kind: Service
apiVersion: v1
metadata:
  name: starlink-service
spec:
  selector:
    app: starlink-container
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort
