apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: starlink-svc-ingress
spec:
  rules:
  - host: "localhost"
    http:
      paths:
      - path: "/starlink"
        backend:
          serviceName: starlink
          servicePort: 80
